---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(polite)
library(purrr)
library(httr2)
library(httr)
library(leaflet)
library(shiny)
library(ggiraph)
```

About
=====================================  

    
Column {data-width=600}
-------------------------------------

Introduction


Team Success {data-orientation=rows}
=====================================     

Column {data-width=650}
-----------------------------------------------------------------------

```{r setup nhl data set, include=FALSE}
robotstxt::paths_allowed("https://www.hockey-reference.com/leagues/NHL_2026.html")

#Step One
nhl <- read_html("https://www.hockey-reference.com/leagues/NHL_2026.html")
str(nhl)

#Step Two
table <- html_nodes(nhl, css = "table")
untidy_tables <- html_table(table, header = TRUE, fill = TRUE)

scrape <- function(x) {
  url <- read_html(str_c("https://www.hockey-reference.com/leagues/NHL_", x, ".html")) 
  table <- html_nodes(url, css = "table")
  untidy_tables <- html_table(table, header = TRUE, fill = TRUE) 
  eastern <- untidy_tables[[1]] |>                   # tidy eastern conference
    rename(Team = 1) |>                              # rename first column      
    slice(-1, -10)                                   # remove unnecessary rows
  western <- untidy_tables[[2]] |>                   # tidy western conference
    rename(Team = 1) |>                              # rename first column
    slice(-1, -10)                                   # remove unnecessary rows
  full_standings <- western |>                       # join eastern and western
    full_join(eastern) |>
    mutate(season = x)
  full_standings
}

# Create df to sort conference and divisions
nhl_conferences <- data.frame(
  Team = c("Boston Bruins", "Buffalo Sabres", "Detroit Red Wings", "Florida Panthers", "Montreal Canadiens", "Ottawa Senators", "Tampa Bay Lightning", "Toronto Maple Leafs","Carolina Hurricanes", "Columbus Blue Jackets", "New Jersey Devils", "New York Islanders", "New York Rangers", "Philadelphia Flyers", "Pittsburgh Penguins", "Washington Capitals", "Chicago Blackhawks", "Colorado Avalanche", "Dallas Stars", "Minnesota Wild", "Nashville Predators", "St. Louis Blues", "Utah Mammoth", "Winnipeg Jets", "Anaheim Ducks", "Calgary Flames", "Edmonton Oilers", "Los Angeles Kings", "San Jose Sharks", "Seattle Kraken", "Vancouver Canucks", "Vegas Golden Knights"),
  conference = c(rep("Eastern", 16), rep("Western", 16)),
  division = c(rep("Atlantic", 8), rep("Metropolitan", 8), rep("Central", 8), rep("Pacific", 8)))

nhl_full_years <- map_df(2022:2026, scrape)

# clean names and levels
nhl_full_years <- nhl_full_years |>
  rename(PTS_PCT = `PTS%`,
         RPt_PCT = `RPt%`,
         RgPT_PCT = `RgPt%`) |>
  mutate(across(GP:RW, as.numeric),
         RgPT_PCT = as.numeric(RgPT_PCT),
         Team = str_replace(Team, "\\*", ""),
         W_PCT = (W / GP),          # create new vars
         W_PCT = round(W_PCT, 4))

nhl_all <- nhl_full_years |>
  left_join(nhl_conferences) # add conferences and divisions
```

```{r location data, include=FALSE}
robotstxt::paths_allowed("https://en.wikipedia.org/wiki/List_of_National_Hockey_League_arenas")

# Scraping arenas and team name
locations <- read_html("https://en.wikipedia.org/wiki/List_of_National_Hockey_League_arenas")
str(locations)

table <- html_nodes(locations, css = "table")                   # scrape tables from wiki
untidy_tables <- html_table(table, header = TRUE, fill = TRUE)  

location_tbl <- untidy_tables[[1]] |>           # 
  rename(Image = 1, arena = 2, location = 3,
         team = 4, capacity = 5, opened = 6,
         season_one = 7, refs = 8) |>
  select(arena, team) |>
  mutate(arena = str_replace(arena, " ", "_"),
         arena = str_replace(arena, " ", "_"))

# test scrape coordinates
coord <- read_html("https://en.wikipedia.org/wiki/PPG_Paints_Arena")
lat_temp <- html_nodes(coord, ".rt-overlay , #mw-content-text .latitude")
lat_text <- html_text(lat_temp)

long_temp <- html_nodes(coord, ".rt-overlay , #mw-content-text .longitude")
long_text <- html_text(long_temp)

coordinates <- tibble(lat = lat_text,
                      long = long_text)

# create arena list
arenas_col <- location_tbl |> 
  select(arena) |>
  mutate(arena = str_replace(arena, " ", "_"),
         arena = str_replace(arena, " ", "_"))
arena <-as.list(arenas_col)

# for loop for coordinates
coordinates <- tibble(latitude = character(), longitude = character(), arena = character())

for(i in 1:32) {
  url <- str_c("https://en.wikipedia.org/wiki/", arena[[1]][i])
  one_arena <- GET(url)
  coord <- read_html(one_arena)
# latitude scrape
  lat_temp <- html_nodes(coord, ".rt-overlay , #mw-content-text .latitude")
  lat_text <- html_text(lat_temp)
# longitude scrape
  long_temp <- html_nodes(coord, ".rt-overlay , #mw-content-text .longitude")
  long_text <- html_text(long_temp)

  coordinates[i,1] <- lat_text[1]
  coordinates[i,2] <- long_text[1]
  coordinates[i,3] <- arena[[1]][i]
}

# join two dfs
locations <- location_tbl |>
  full_join(coordinates) |>
  mutate(arena = str_replace(arena, "_", " "), # clean arena names
         arena = str_replace(arena, "_", " "))

# clean latitude and longitude for map
fix_lat_long <- function(x) {
  degree  <- as.numeric(str_extract(x, "^[0-9.]+"))
  minutes <- as.numeric(str_extract(x, "[0-9.]+(?=′)"))
  seconds <- as.numeric(str_extract(x, "[0-9.]+(?=″)"))
  decimal <- degree + minutes/60 + seconds/3600
  return(decimal)
}

locations_clean <- locations |>
  mutate(latitude = sapply(latitude, fix_lat_long),
    longitude = sapply(longitude, fix_lat_long),
    longitude = as.numeric(str_c("-",longitude)))

# Join locations to NHL data
locations_clean <- locations_clean |> 
  rename(Team = team)                 # match variable name

nhl_map <- nhl_full_years |>
  full_join(locations_clean) |>
    mutate(W_PCT = W_PCT * 100,
         W_PCT_map_size = (as.numeric(W) / as.numeric(GP)) * 30,
         popup = str_c(arena, ": the ", Team, " have a win percentage of ", W_PCT, "%")) 
```

```{r, echo=FALSE}
inputPanel(
  selectInput("chosen_stat", label = "Choose a Statistic:",
              choices = c("Number of Wins" = "W", 
                          "Number of Losses" = "L",
                          "Win Percentage" = "W_PCT",
                          "Points" = "PTS",
                          "Goals For" = "GF",
                          "Goals Against" = "GA")),
  selectInput("chosen_team", label = "Choose Teams:",
              choices = c(nhl_all$Team), selected = c("Minnesota Wild", "Colorado Avalanche", "Dallas Stars"), multiple = TRUE)
)

renderPlot(
  nhl_all |>
    filter(Team %in% input$chosen_team) |>
    ggplot(aes(x = season, y = .data[[input$chosen_stat]], color = Team)) +
    geom_point() +
    geom_smooth() +
    labs(x = "Season",
         y = "Chosen Statistic")
)
```

Map of Teams
=====================================

```{r, echo = FALSE}
nhl_map_26 <- nhl_map |>
  filter(season == 2026)

bins <- c(0, 30, 40, 50, 60, 70, 80, 100)
pal <- colorBin("YlOrRd", domain = nhl_map$W_PCT, bins = bins)

leaflet() |>
  setView(-97, 40, 4) |>
  addTiles() |>
  addCircleMarkers(data = nhl_map_26,
        lat = ~ latitude, 
        lng = ~ longitude,
        popup = ~ popup,
        radius = ~ W_PCT_map_size,
        weight = 4,
        color = "grey",
        fillColor = ~pal(W_PCT),
        fillOpacity = 1)
```

Row
-------------------------------------

Words


Team Luck
=====================================   

Row
-------------------------------------

```{r, echo = FALSE}
inputPanel(
  selectInput("team_select", label = "Choose a team:",
              choices = c(nhl_all$Team), selected = c("Minnesota Wild")
))

renderPlot(
nhl_all |> 
    mutate(selected = Team == input$team_select) |>
    ggplot(aes(x = W_PCT, y = SRS)) + 
    geom_point(aes(color = selected, size = selected), show.legend = FALSE) +
    geom_smooth(method = lm, se = FALSE) +
    labs(y = "Simple Rating System (SRS)", x = "Winning Percentage")
)
```

Row
-------------------------------------

SRS measures skill!


Conference Strength {data-orientation=rows}
=====================================   

Row
-------------------------------------

```{r density plot, echo=FALSE}
inputPanel(
  selectInput("year", label = "Chose a Season:",
              choices = c(2022, 2023, 2024, 2025, 2026))
)

renderPlot(
  nhl_all |>
    filter(!is.na(conference), 
           season == input$year) |>
    ggplot(aes(x = W_PCT, color = division, fill = division)) +
    geom_density(bw = "nrd0", alpha = 0.4) +
    labs(x = "Winnning Percentage", y = "Density")
)
```

Row
-------------------------------------

Stuff

